In [1]:
import numpy as np
import pandas as pd 

In [2]:
file = r'/Users/lalitsachan/Dropbox/0.0 Data/review_corpus.csv'

In [3]:
td=pd.read_csv(file,encoding='latin-1')

In [4]:
td['label'].value_counts()

__label__1     5097
__label__2     4903
Name: label, dtype: int64

In [5]:
td

text        label
0      Stuning even for the non-gamer: This sound tr...  __label__2 
1      The best soundtrack ever to anything.: I'm re...  __label__2 
2      Amazing!: This soundtrack is my favorite musi...  __label__2 
3      Excellent Soundtrack: I truly like this sound...  __label__2 
4      Remember, Pull Your Jaw Off The Floor After H...  __label__2 
...                                                 ...          ...
9995   A revelation of life in small town America in...  __label__2 
9996   Great biography of a very interesting journal...  __label__2 
9997   Interesting Subject; Poor Presentation: You'd...  __label__1 
9998   Don't buy: The box looked used and it is obvi...  __label__1 
9999   Beautiful Pen and Fast Delivery.: The pen was...  __label__2 

[10000 rows x 2 columns]

In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [7]:
td.shape

(10000, 2)

In [8]:
tfidf=TfidfVectorizer(analyzer='word',stop_words='english',min_df=0.01,max_df=0.6)

In [9]:
tfidf.fit(td['text'])

TfidfVectorizer(max_df=0.6, min_df=0.01, stop_words='english')

In [10]:
tfidf_data=tfidf.transform(td['text'])

In [11]:
tfidf_data

<10000x532 sparse matrix of type '<class 'numpy.float64'>'
	with 147494 stored elements in Compressed Sparse Row format>

In [12]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC

In [13]:
knn=KNeighborsClassifier(n_neighbors=100)
nb=MultinomialNB()
svm=SVC()

In [14]:
from sklearn.model_selection import cross_val_score

In [15]:
cross_val_score(knn,tfidf_data,td['label'],cv=10,scoring='accuracy',n_jobs=-1)

array([0.718, 0.781, 0.717, 0.707, 0.713, 0.704, 0.722, 0.701, 0.73 ,
       0.746])

In [16]:
cross_val_score(nb,tfidf_data,td['label'],cv=10,scoring='accuracy',n_jobs=-1)

array([0.797, 0.81 , 0.774, 0.779, 0.788, 0.778, 0.797, 0.777, 0.803,
       0.803])

In [17]:
cross_val_score(svm,
                tfidf_data,
                td['label'],
                cv=10,
                scoring='accuracy',
                n_jobs=-1)

array([0.826, 0.829, 0.802, 0.803, 0.797, 0.791, 0.804, 0.786, 0.814,
       0.824])

In [18]:
nb.fit(tfidf_data,td['label'])

MultinomialNB()

In [19]:
predicted=nb.predict(tfidf_data)

In [20]:
pd.crosstab(td['label'],predicted,margins=True)

col_0        __label__1   __label__2     All
label                                       
__label__1          4189          908   5097
__label__2           872         4031   4903
All                 5061         4939  10000

In [28]:
svm=SVC(probability=True)

In [29]:
svm.fit(tfidf_data,td['label'])
svm.predict_proba(tfidf_data)

array([[0.08359671, 0.91640329],
       [0.08369064, 0.91630936],
       [0.02311297, 0.97688703],
       ...,
       [0.98530818, 0.01469182],
       [0.99087573, 0.00912427],
       [0.05095046, 0.94904954]])